### ISSUE TITLE
support for configuraton: forced to enter z_offset

### ISSUE THREAD

**Issue by limefrog-the-genuine-one** [jniebuhr/adxl345-probe#11]
Hi,

i'm up to install and configure the adxl345-probing, but surely need a bit of support. First thing happened after injecting the [adxl345-probe] section:

> Klipper meldet: ERROR
> Option 'z_offset' in section 'adxl345_probe' must be specified

So i added

`z_offset: 0`

to that section and Klipper accepted that (I'd like to propose to add that to the code-snippet you provide).

I declared the 'adxl345_probe' as endstop for the Z-axis:

```
[stepper_z]
…
endstop_pin: probe:adxl345_probe
…
```

Then i get:

> Klipper meldet: ERROR
> Probe virtual endstop only useful as endstop pin

so i'd like to ask for some support in getting this running and tuned.
I'll add some snippets of my config below for reference, hardware is: BTT Manta M8P & CB1

Kind Regards
limefrog

 
```
[mcu cb1]
serial: /tmp/klipper_host_mcu

[adxl345]
axes_map: x,y,z
cs_pin: cb1:gpio200
spi_bus: spidev1.1

…

[stepper_z] # Motor4
step_pin: PD3
dir_pin: !PD2
enable_pin: !PD5
microsteps: 128
rotation_distance: 2
endstop_pin: probe:adxl345_probe
position_endstop: 0
position_max: 510
position_min: -3
homing_speed: 3 # 12.5
second_homing_speed: 1
homing_retract_speed: 2
homing_retract_dist: 5

…

[resonance_tester]
accel_chip: adxl345
probe_points:
   170,185,20

[adxl345_probe]
probe_pin: PF5 # pin for either int1 or int2
int_pin: int1 # select either int1 or int2, depending on your choice of wiring
tap_thresh: 12000 # this needs to be tuned
tap_dur: 0.01 # this needs to be tuned
speed: 20 # this needs to be tuned
# Adjust this to your liking
samples: 3
sample_retract_dist: 3.0
samples_result: median
samples_tolerance: 0.01
samples_tolerance_retries: 20
z_offset: 0
```

**Comment by Life0fBrian** [comment]
Please use the following for the endstop_pin definition:
`probe:z_virtual_endstop`

Could have sent you my config snippet. 😉

**Comment by limefrog-the-genuine-one** [comment]
Well that helped, thanks a lot…

…but now i get:

> Klipper meldet: ERROR
> Option 'position_endstop' is not valid in section 'stepper_z'

i have that set to 0 so far.

**Comment by limefrog-the-genuine-one** [comment]
Think i really should ask for your config snippet. :sunglasses:

**Comment by jniebuhr** [comment]
You have to remove position_endstop when using a virtual endstop since that is automatically taken from z_offset of the probe

**Comment by jniebuhr** [comment]
added the config in the readme
