### ISSUE TITLE
License violation by the Cartographer project

### ISSUE THREAD

**Issue by Zeanon** [jniebuhr/adxl345-probe#12]
Just as a heads up, the carto project is using your code without giving attribution(which is required with cc), dont know if you want to do anything about it, just letting you know
https://github.com/Cartographer3D/cartographer-klipper/blob/master/scanner.py#L1496
https://github.com/Cartographer3D/cartographer-klipper/blob/master/scanner.py#L2394
https://github.com/Cartographer3D/cartographer-klipper/blob/master/scanner.py#L2535

**Comment by jniebuhr** [comment]
Hiya, can you post examples? Or is it just single lines?

**Comment by Zeanon** [comment]
well, I have to update the links I suppose, code changed, give me a sec

**Comment by Zeanon** [comment]
ok, correction
they removed the code again so currently it doesnt matter:
https://github.com/Cartographer3D/cartographer-klipper/commit/c1d8327b42cd61336877d37fd628bb1f4fd73f29
I would still keep an eye on that though

**Comment by jniebuhr** [comment]
Thanks! I’ll talk to them about it. It’s the second time in the last weeks this happens with some stuff 😅

**Comment by Jomik** [comment]
I'm unsure if that was gathered from this - I know it was meant to be removed before release.
I joined the project after, so unsure.
But since all modifications of Klipper needs to be licensed under GPLv3, where attribution is not required, then I don't think there's an issue. 🤔

**Comment by Zeanon** [comment]
> I'm unsure if that was gathered from this - I know it was meant to be removed before release.
> I joined the project after, so unsure.
> But since all modifications of Klipper needs to be licensed under GPLv3, where attribution is not required, then I don't think there's an issue. 🤔

The code that was in carto looks to be the same as the adxl probe Code
Which is licensed under CC 
While cc is definitely not an optimal license for open source code it still has to be respected 
I'll leave it to the owner of this project how to proceed, I just noticed something that looks like a license violation to me and reported it, everything else I can't do anything about

**Comment by Jomik** [comment]
In this I totally agree. I don't know the source, but agree with this. It should always be attributed.
Personally I add attributions even if no license requires it.
I'm unsure about the origin here, but I know that the functionality was scraped - the code should probably never have been released.

**Comment by yell3D** [comment]
To me it looks like it slipped from Richards prototyping bench into the survey release https://github.com/Cartographer3D/cartographer-klipper/commit/e990562fde20c19918ae2e800c18389728ce75cc 

Likely forgot to remove it because of stress and dozen of people asking "tap, wen".
Wasnt used, couldnt be used, its gone, fine now ¯\\\_(ツ)\_/¯
