### ISSUE TITLE
Missing GPLv3 license

### ISSUE THREAD

**Issue by Jomik** [jniebuhr/adxl345-probe#13]
Hey, as I mentioned in the discord, you should be aware that derivatives of Klipper are required to be licensed under GPLv3.
Thus this project is in violation of the Klipper license which is it clearly derived from 😊

**Comment by Zeanon** [comment]
> Hey, as I mentioned in the discord, you should be aware that derivatives of Klipper are required to be licensed under GPLv3.
> Thus this project is in violation of the Klipper license which is it clearly derived from 😊

Since I feel like this is related to my report:
This code is not directly accessing any Klipper code, so it does not have to be GPL.
It is a standalone piece of software.
The relative imports in the code are not bound to be klipper

**Comment by Jomik** [comment]
I can follow the argument, but I think the initial probe class looks alot like the Klipper probe.
I also think the general consensus is that with the current state of Klipper extras, it is a modification of Klipper.
You're choosing to ship just the changes separately, but for the user to use it they have to apply the modification which is in the install script.
So the shipped program is a Klipper derivative, even if the modification is separate.
If this is not the case, then the license loses its meaning..

**Comment by Jomik** [comment]
Well, I don't represent Cartographer..
I'm agreeing with you, that attributions should be made, but also saying that I'm unaware of the actual source. It's before my time as a contributor..
I gave my interpretation of the licensing, hoping we could stick to that, as that is what seems to be relevant to this issue.

You opened this well aware that the offending code was removed too. I guess I got baited.

**Comment by Jomik** [comment]
Closing this as it's drifted from the original purpose. I believe @jniebuhr is aware of the of the licensing issue in their own project and this is not contributing to a constructive discussion about it, but rather a headhunt on cartographer.
