### ISSUE TITLE
BTT EBB 36 support

### ISSUE THREAD

**Issue by pwilkowski** [jniebuhr/adxl345-probe#3]
Hello, could support for the canbus board be added as in title? Its similar to SHT36, thanks.

**Comment by jniebuhr** [comment]
Hi, the supported boards in the Readme are not the ones I support in my Software, they’re the ones where the correct Traces were added. On an EBB36, none of the INT pins of the ADXL345 are connected to anything. So it doesn’t work. You can solder a tiny wire if you’re good at microsoldering.

**Comment by pwilkowski** [comment]
@jniebuhr yes i did see int pins arent connected but i can solder thin wire, question is, does it have to be EXTI (hardware interrupt capable) pin or it does work but continuously scanning them?

**Comment by jniebuhr** [comment]
i'm not sure about that. it's somewhere in the klipper c code. if one of those is available i'd rather say use it if it does need it

**Comment by pwilkowski** [comment]
i checked the gpio code and doesnt seem like klipper uses any irq/exti functionality but maybe i am wrong, anyways i did solder wire to PB13
![](https://i.imgur.com/ly4NPDb.png)

So i guess i can try?

**Comment by pwilkowski** [comment]
Discord invite link has expired

**Comment by jniebuhr** [comment]
Fixed

**Comment by WayneManion** [comment]
Very impressive soldering work!

**Comment by Slatkey** [comment]
> i checked the gpio code and doesnt seem like klipper uses any irq/exti functionality but maybe i am wrong, anyways i did solder wire to PB13 ![](https://camo.githubusercontent.com/e4a075369081c7ceb93f919ce6c6ce43916c6448f258336bc2a1f5951a0329c8/68747470733a2f2f692e696d6775722e636f6d2f6c79344e5044622e706e67)
> 
> So i guess i can try?

Hi. Did you manage to check the operation of the accelerometer? I want to repeat your soldering feat

**Comment by pwilkowski** [comment]
@Slatkey yes it does work but not on the pin you see on the picture, i had to change to different pin as PB13 is used as heater, however i found it unreliable and changed probe to klicky.
